version: '3.8'

services:
 zedge:
  build:
   context: .
  ports:
   - 5000:5000
  #  - 9229:9229
  environment:
   - PORT=5000
   - MONGO_DATABASE=mongodb://mongo:27017/zedge
  volumes:
   - ./:/code
  command: npm run start

 mongo:
  image: mongo
  ports:
   - 27017:27017
  volumes:
   - mongodb:/data/db
   - mongodb_config:/data/configdb
volumes:
 mongodb:
 mongodb_config: